# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ExcalidrawDecrypt < Formula
  desc "Library and CLI to decrypt excalidraw diagrams from shareable links"
  homepage "https://github.com/loveholidays/excalidraw-decrypt"
  version "0.6.0"
  license "LGPL-3.0-or-later"

  on_macos do
    on_intel do
      url "https://github.com/loveholidays/excalidraw-decrypt/releases/download/v0.6.0/excalidraw-decrypt_0.6.0_darwin_amd64.tar.gz"
      sha256 "6eb7114dc8e2d77d08d6ae9b7759e51bd78cd67692a87c04f809d2edaee3d3ca"

      def install
        bin.install "excalidraw-decrypt"
      end
    end
    on_arm do
      url "https://github.com/loveholidays/excalidraw-decrypt/releases/download/v0.6.0/excalidraw-decrypt_0.6.0_darwin_arm64.tar.gz"
      sha256 "4da46522ea59c9fde38269fe6c84b0e21ec845dced1e37f8abe548613232908b"

      def install
        bin.install "excalidraw-decrypt"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/loveholidays/excalidraw-decrypt/releases/download/v0.6.0/excalidraw-decrypt_0.6.0_linux_amd64.tar.gz"
        sha256 "a47bf3873a842c25eedd4efc17236f41f488dccb27442b7c768e64dcea423ce9"

        def install
          bin.install "excalidraw-decrypt"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/loveholidays/excalidraw-decrypt/releases/download/v0.6.0/excalidraw-decrypt_0.6.0_linux_arm64.tar.gz"
        sha256 "7e8ed04d2eccb7b9fd47f93f9bb7289cb5f7986f8ae7ef61782103f46b243cb5"

        def install
          bin.install "excalidraw-decrypt"
        end
      end
    end
  end
end
