# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/gcs_download_strategy"
class Lvh < Formula
  desc "Loveholidays CLI, help your automate your day to day tasks in Loveholidays"
  homepage "https://github.com/loveholidays/lvh"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.arm?
      url "gs://lh-homebrew-bin/lvh/v0.0.4/lvh_darwin_arm64.tar.gz", using: GcsDownloadStrategy
      sha256 "a2077981442c1bbcb9d8888b283dce106234cd85299aac9382e222b6b81504cc"

      def install
        bin.install "lvh"
      end
    end
    if Hardware::CPU.intel?
      url "gs://lh-homebrew-bin/lvh/v0.0.4/lvh_darwin_x86_64.tar.gz", using: GcsDownloadStrategy
      sha256 "cdc11665e0f2e5b4d14819354fd4f4fc50da231a083ba4e4d41ebeba0857739d"

      def install
        bin.install "lvh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "gs://lh-homebrew-bin/lvh/v0.0.4/lvh_linux_x86_64.tar.gz", using: GcsDownloadStrategy
      sha256 "211e43fcd17e49aad0546ebcdaca6afc264ef474d7a52a56a9578e697cb6bda4"

      def install
        bin.install "lvh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "gs://lh-homebrew-bin/lvh/v0.0.4/lvh_linux_arm64.tar.gz", using: GcsDownloadStrategy
      sha256 "a6ee6b900eab6e9abfebfbdfe757f6869b33673afd139d0f245c4e8b31bdfccf"

      def install
        bin.install "lvh"
      end
    end
  end
end
