# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PoTest < Formula
  desc "CLI to run unit tests against prometheus-operator manifests"
  homepage "https://github.com/loveholidays/po-test"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/loveholidays/po-test/releases/download/v0.2.0/po-test_0.2.0_darwin_amd64.tar.gz"
      sha256 "5c95c32ad0f0596f7b36ce933aea33d2bd0f6df6ab1a125bdf636d79f622e2eb"

      def install
        bin.install "po-test"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/loveholidays/po-test/releases/download/v0.2.0/po-test_0.2.0_darwin_arm64.tar.gz"
      sha256 "41ffddd81706ac062b7230b5722d2eef55065d761a60f29934c7c7e58d1a0da5"

      def install
        bin.install "po-test"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/loveholidays/po-test/releases/download/v0.2.0/po-test_0.2.0_linux_arm64.tar.gz"
      sha256 "c32f0ca250c0b62a841c3d01f960f25fa95dac7f91cd9884ea2995666f19f02c"

      def install
        bin.install "po-test"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/loveholidays/po-test/releases/download/v0.2.0/po-test_0.2.0_linux_amd64.tar.gz"
      sha256 "4f5e5421f83adbedb0522afd8211558cf82da5fc283ab6a985c76b6777f35d03"

      def install
        bin.install "po-test"
      end
    end
  end
end
