# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PoTest < Formula
  desc "CLI to run unit tests against prometheus-operator manifests"
  homepage "https://github.com/loveholidays/po-test"
  version "0.3.0"
  license "LGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/loveholidays/po-test/releases/download/v0.3.0/po-test_0.3.0_darwin_amd64.tar.gz"
      sha256 "ab7b23a097e898b17c4d3977c0534d5ffd6a8570471411ab2ede630ccfaee026"

      def install
        bin.install "po-test"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/loveholidays/po-test/releases/download/v0.3.0/po-test_0.3.0_darwin_arm64.tar.gz"
      sha256 "6429aaee42242c6c8e8cbca6a60c3b89895ab6bfff7d286ddcff784dbbf4823c"

      def install
        bin.install "po-test"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/loveholidays/po-test/releases/download/v0.3.0/po-test_0.3.0_linux_arm64.tar.gz"
      sha256 "14efbff9fb542834bdbbb6fe1a1e626db3966dbc2323845a23442c0b849e96e3"

      def install
        bin.install "po-test"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/loveholidays/po-test/releases/download/v0.3.0/po-test_0.3.0_linux_amd64.tar.gz"
      sha256 "8318e37163cb480297d7d67f6b0e84d56cfc2deaeaac2469b52a4a928c174521"

      def install
        bin.install "po-test"
      end
    end
  end
end
