# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PoTest < Formula
  desc "CLI to run unit tests against prometheus-operator manifests"
  homepage "https://github.com/loveholidays/po-test"
  version "0.2.0"
  license "LGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/loveholidays/po-test/releases/download/v0.2.0/po-test_0.2.0_darwin_amd64.tar.gz"
      sha256 "6fb3a524a3e121c315962a22189c0ec9e0467c3410561ff94586b7c93969de54"

      def install
        bin.install "po-test"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/loveholidays/po-test/releases/download/v0.2.0/po-test_0.2.0_darwin_arm64.tar.gz"
      sha256 "ae2a0205ba1ebe64a633a814162784acd32470c931513d050d439ba2da8cbd33"

      def install
        bin.install "po-test"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/loveholidays/po-test/releases/download/v0.2.0/po-test_0.2.0_linux_arm64.tar.gz"
      sha256 "2db79886310ab37bdfefa54bb1ea202c2290f7411871bdf1ba939121504df18e"

      def install
        bin.install "po-test"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/loveholidays/po-test/releases/download/v0.2.0/po-test_0.2.0_linux_amd64.tar.gz"
      sha256 "84f66ef4059252d21fd9fbaed59ea450d68d50436ff793ac145be4b827d600d8"

      def install
        bin.install "po-test"
      end
    end
  end
end
