# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ripley < Formula
  desc "Replays HTTP traffic at multiples of the original rate"
  homepage "https://github.com/loveholidays/ripley"
  version "0.0.8"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/loveholidays/ripley/releases/download/v0.0.8/ripley_Darwin_x86_64.tar.gz"
      sha256 "e4cc8e6ee6f9a28bbac7c46ea2147c56fde72b3ad5c83529449d38599dda5001"

      def install
        bin.install "ripley"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/loveholidays/ripley/releases/download/v0.0.8/ripley_Darwin_arm64.tar.gz"
      sha256 "ac336166ff75da079e0e37504d7771c864123ed717c34abb2aa792495c05f0da"

      def install
        bin.install "ripley"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/loveholidays/ripley/releases/download/v0.0.8/ripley_Linux_arm64.tar.gz"
      sha256 "97044c4f4de5de58f54bbd5311a35afad9a66612d1f4f817cd078f5fc94a1899"

      def install
        bin.install "ripley"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/loveholidays/ripley/releases/download/v0.0.8/ripley_Linux_x86_64.tar.gz"
      sha256 "796a26b320e8b151f8b39e6dadd2c970c733a5d2b64d691ef959a0947101a331"

      def install
        bin.install "ripley"
      end
    end
  end
end
