# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ripley < Formula
  desc "Replays HTTP traffic at multiples of the original rate"
  homepage "https://github.com/loveholidays/ripley"
  version "0.1.2"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/loveholidays/ripley/releases/download/v0.1.2/ripley_Darwin_x86_64.tar.gz"
      sha256 "b06a7f9fc511c99c7ec41d295a070408331e2d40e7e8a50b91625bf577beabd8"

      def install
        bin.install "ripley"
      end
    end
    on_arm do
      url "https://github.com/loveholidays/ripley/releases/download/v0.1.2/ripley_Darwin_arm64.tar.gz"
      sha256 "e4d7fd2861725a335306404726f844e55b61c83f78447e7f5fc6d0c8abbd86db"

      def install
        bin.install "ripley"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/loveholidays/ripley/releases/download/v0.1.2/ripley_Linux_x86_64.tar.gz"
        sha256 "7d74fbd052e1160e3e91923cb34da3d407c4b05e1241a06e0bb7e3b359861ad2"

        def install
          bin.install "ripley"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/loveholidays/ripley/releases/download/v0.1.2/ripley_Linux_arm64.tar.gz"
        sha256 "ee902c7a2e732b012ced2914d173dee7401da87599fd235a80b2d723a3451368"

        def install
          bin.install "ripley"
        end
      end
    end
  end
end
